config {
    type: "table",
    schema: "TRUSTED_FLATFILE",
    tags: ['escolas_full', 'processo_full'],
    name: "api_escolas_trusted",
    description: "Tabela criada a partir de RAW_FLATFILE.api_escolas",
    bigquery: {
        partitionBy: "DATETIME_TRUNC(partition_time, MONTH)",
        clusterBy: ['cod'],
    },
    dependencies: [
        'api_escolas_raw'
    ]
}

WITH latest_partition AS (
    SELECT MAX(partition_time) AS max_partition_time
    FROM `logical-essence-433414-r5.RAW_FLATFILE.api_escolas_raw`
)

select 
  CAST(cod AS STRING) AS cod,
  PARSE_DATE('%Y', CAST(ano_censo AS STRING)) AS ano_censo,
  CAST(nome AS STRING) AS nome,
  CAST(situacao_funcionamento AS INT64) AS situacao_funcionamento,
  CAST(situacao_censo AS INT64) AS situacao_censo,
  CAST(inicio_ano AS STRING) AS inicio_ano,
  CAST(fim_ano AS STRING) AS fim_ano,
  CAST(cod_uf AS INT64) AS cod_uf,
  CAST(sigla_uf AS STRING) AS sigla_uf,
  CAST(cod_municipio AS STRING) AS cod_municipio,
  CAST(nome_municipio AS STRING) AS nome_municipio,
  CAST(cod_distrito AS INT64) AS cod_distrito,
  CAST(nome_distrito AS STRING) AS nome_distrito,
  CAST(regiao AS STRING) AS regiao,
  CAST(dependencia_administrativa AS INT64) AS dependencia_administrativa,
  CAST(tipo_localizacao AS INT64) AS tipo_localizacao,
  CAST(regulamentada AS INT64) AS regulamentada,
  CAST(agua_filtrada AS BOOL) AS agua_filtrada,
  CAST(agua_publica AS BOOL) AS agua_publica,
  CAST(agua_poco_artesiano AS BOOL) AS agua_poco_artesiano,
  CAST(agua_cacimba AS BOOL) AS agua_cacimba,
  CAST(agua_rio AS BOOL) AS agua_rio,
  CAST(agua_inexistente AS BOOL) AS agua_inexistente,
  CAST(energia_publica AS BOOL) AS energia_publica,
  CAST(energia_gerador AS BOOL) AS energia_gerador,
  CAST(energia_outros AS BOOL) AS energia_outros,
  CAST(energia_inexistente AS BOOL) AS energia_inexistente,
  CAST(esgoto_publico AS BOOL) AS esgoto_publico,
  CAST(esgoto_fossa AS BOOL) AS esgoto_fossa,
  CAST(esgoto_inexistente AS BOOL) AS esgoto_inexistente,
  CAST(lixo_coleta_periodica AS BOOL) AS lixo_coleta_periodica,
  CAST(lixo_queima AS BOOL) AS lixo_queima,
  CAST(lixo_joga_outra_area AS BOOL) AS lixo_joga_outra_area,
  CAST(lixo_recicla AS BOOL) AS lixo_recicla,
  CAST(lixo_enterra AS BOOL) AS lixo_enterra,
  CAST(lixo_outros AS BOOL) AS lixo_outros,
  CAST(sala_diretoria AS BOOL) AS sala_diretoria,
  CAST(sala_professores AS BOOL) AS sala_professores,
  CAST(laboratorio_informatica AS BOOL) AS laboratorio_informatica,
  CAST(laboratorio_ciencias AS BOOL) AS laboratorio_ciencias,
  CAST(atendimento_especial AS BOOL) AS atendimento_especial,
  CAST(quadra_coberta AS BOOL) AS quadra_coberta,
  CAST(quadra_descoberta AS BOOL) AS quadra_descoberta,
  CAST(cozinha AS BOOL) AS cozinha,
  CAST(biblioteca AS BOOL) AS biblioteca,
  CAST(sala_leitura AS BOOL) AS sala_leitura,
  CAST(parque_infantil AS BOOL) AS parque_infantil,
  CAST(bercario AS BOOL) AS bercario,
  CAST(sanitario_fora_predio AS BOOL) AS sanitario_fora_predio,
  CAST(sanitario_dentro_predio AS BOOL) AS sanitario_dentro_predio,
  CAST(sanitario_educ_infant AS BOOL) AS sanitario_educ_infant,
  CAST(sanitario_pne AS BOOL) AS sanitario_pne,
  CAST(dependencias_pne AS BOOL) AS dependencias_pne,
  CAST(secretaria AS BOOL) AS secretaria,
  CAST(banheiro_chuveiro AS BOOL) AS banheiro_chuveiro,
  CAST(refeitorio AS BOOL) AS refeitorio,
  CAST(despensa AS BOOL) AS despensa,
  CAST(almoxarifado AS BOOL) AS almoxarifado,
  CAST(auditorio AS BOOL) AS auditorio,
  CAST(patio_coberto AS BOOL) AS patio_coberto,
  CAST(patio_descoberto AS BOOL) AS patio_descoberto,
  CAST(alojamento_aluno AS BOOL) AS alojamento_aluno,
  CAST(alojamento_professor AS BOOL) AS alojamento_professor,
  CAST(area_verde AS BOOL) AS area_verde,
  CAST(lavanderia AS BOOL) AS lavanderia,
  CAST(salas_existentes AS INT64) AS salas_existentes,
  CAST(salas_utilizadas AS INT64) AS salas_utilizadas,
  CAST(televisores AS INT64) AS televisores,
  CAST(video_cassetes AS INT64) AS video_cassetes,
  CAST(dvds AS INT64) AS dvds,
  CAST(parabolicas AS INT64) AS parabolicas,
  CAST(copiadoras AS INT64) AS copiadoras,
  CAST(retroprojetores AS INT64) AS retroprojetores,
  CAST(impressoras AS INT64) AS impressoras,
  CAST(aparelhos_som AS INT64) AS aparelhos_som,
  CAST(data_shows AS INT64) AS data_shows,
  CAST(fax AS INT64) AS fax,
  CAST(foto AS INT64) AS foto,
  CAST(computadores AS INT64) AS computadores,
  CAST(computadores_adm AS INT64) AS computadores_adm,
  CAST(computadores_alunos AS INT64) AS computadores_alunos,
  CAST(internet AS BOOL) AS internet,
  CAST(banda_larga AS BOOL) AS banda_larga,
  CAST(funcionarios AS INT64) AS funcionarios,
  CAST(alimentacao AS BOOL) AS alimentacao,
  CAST(aee AS BOOL) AS aee,
  CAST(atividade_complementar AS INT64) AS atividade_complementar,
  CAST(ensino_regular AS BOOL) AS ensino_regular,
  CAST(reg_creche AS BOOL) AS reg_creche,
  CAST(reg_preescola AS BOOL) AS reg_preescola,
  CAST(reg_fundamental8 AS BOOL) AS reg_fundamental8,
  CAST(reg_fundamental19 AS BOOL) AS reg_fundamental19,
  CAST(reg_medio_medio AS BOOL) AS reg_medio_medio,
  CAST(reg_medio_integrado AS BOOL) AS reg_medio_integrado,
  CAST(reg_medio_normal AS BOOL) AS reg_medio_normal,
  CAST(reg_medio_profissional AS BOOL) AS reg_medio_profissional,
  CAST(ensino_especial AS BOOL) AS ensino_especial,
  CAST(esp_creche AS BOOL) AS esp_creche,
  CAST(esp_preescola AS BOOL) AS esp_preescola,
  CAST(esp_fundamental8 AS BOOL) AS esp_fundamental8,
  CAST(esp_fundamental9 AS BOOL) AS esp_fundamental9,
  CAST(esp_medio_medio AS BOOL) AS esp_medio_medio,
  CAST(esp_medio_integrado AS BOOL) AS esp_medio_integrado,
  CAST(esp_medio_normal AS BOOL) AS esp_medio_normal,
  CAST(esp_medio_profissional AS BOOL) AS esp_medio_profissional,
  CAST(esp_eja_fundamental AS BOOL) AS esp_eja_fundamental,
  CAST(esp_eja_medio AS BOOL) AS esp_eja_medio,
  CAST(ensino_eja AS BOOL) AS ensino_eja,
  CAST(eja_fundamental AS BOOL) AS eja_fundamental,
  CAST(eja_medio AS BOOL) AS eja_medio,
  CAST(eja_pro_jovem AS BOOL) AS eja_pro_jovem,
  CAST(ciclos AS BOOL) AS ciclos,
  CAST(fim_de_semana AS BOOL) AS fim_de_semana,
  CAST(pedagogia_alternancia AS BOOL) AS pedagogia_alternancia,
  CAST(ideb_ai AS FLOAT64) AS ideb_ai,
  CAST(ideb_af AS FLOAT64) AS ideb_af,
  CAST(enem_portugues AS FLOAT64) AS enem_portugues,
  CAST(enem_matematica AS FLOAT64) AS enem_matematica,
  CAST(enem_humanas AS FLOAT64) AS enem_humanas,
  CAST(enem_naturais AS FLOAT64) AS enem_naturais,
  CAST(enem_redacao AS FLOAT64) AS enem_redacao,
  CAST(enem_media_objetiva AS FLOAT64) AS enem_media_objetiva,
  CAST(enem_media_geral AS FLOAT64) AS enem_media_geral,
  CAST(socio_economico AS STRING) AS socio_economico,
  CAST(formacao_docente AS FLOAT64) AS formacao_docente,
  CAST(endereco AS STRING) AS endereco,
  CAST(latitude AS STRING) AS latitude,
  CAST(longitude AS STRING) AS longitude,
  CAST(nome_titulo AS STRING) AS nome_titulo,
  CAST(situacao_funcionamento_txt AS STRING) AS situacao_funcionamento_txt,
  PARSE_DATE('%d/%m/%Y', CAST(inicio_ano_txt AS STRING)) AS inicio_ano_txt,
  PARSE_DATE('%d/%m/%Y', CAST(fim_ano_txt AS STRING)) AS fim_ano_txt,
  CAST(dependencia_administrativa_txt AS STRING) AS dependencia_administrativa_txt,
  CAST(tipo_localizacao_txt AS STRING) AS tipo_localizacao_txt,
  CAST(regulamentada_txt AS STRING) AS regulamentada_txt,
  partition_time
  from `logical-essence-433414-r5.RAW_FLATFILE.api_escolas_raw`
  WHERE partition_time = (SELECT max_partition_time FROM latest_partition)






