config {
    type: "incremental",
    schema: "RAW_FLATFILE",
     tags: ['escolas_full', 'processo_full'],
    name: "api_escolas_raw",
    description: "Tabela criada a partir de LAND_FLATFILE.api_escolas",
    bigquery: {
        partitionBy: "DATETIME_TRUNC(partition_time, MONTH)",
        clusterBy: ['cod']
    }
}

WITH cte_raw as (
    select
    cod,
    ano_censo,
    nome,
    situacao_funcionamento,
    situacao_censo,
    inicio_ano,
    fim_ano,
    cod_uf,
    sigla_uf,
    cod_municipio,
    nome_municipio,
    cod_distrito,
    nome_distrito,
    regiao,
    dependencia_administrativa,
    tipo_localizacao,
    regulamentada,
    agua_filtrada,
    agua_publica,
    agua_poco_artesiano,
    agua_cacimba,
    agua_rio,
    agua_inexistente,
    energia_publica,
    energia_gerador,
    energia_outros,
    energia_inexistente,
    esgoto_publico,
    esgoto_fossa,
    esgoto_inexistente,
    lixo_coleta_periodica,
    lixo_queima,
    lixo_joga_outra_area,
    lixo_recicla,
    lixo_enterra,
    lixo_outros,
    sala_diretoria,
    sala_professores,
    laboratorio_informatica,
    laboratorio_ciencias,
    atendimento_especial,
    quadra_coberta,
    quadra_descoberta,
    cozinha,
    biblioteca,
    sala_leitura,
    parque_infantil,
    bercario,
    sanitario_fora_predio,
    sanitario_dentro_predio,
    sanitario_educ_infant,
    sanitario_pne,
    dependencias_pne,
    secretaria,
    banheiro_chuveiro,
    refeitorio,
    despensa,
    almoxarifado,
    auditorio,
    patio_coberto,
    patio_descoberto,
    alojamento_aluno,
    alojamento_professor,
    area_verde,
    lavanderia,
    salas_existentes,
    salas_utilizadas,
    televisores,
    video_cassetes,
    dvds,
    parabolicas,
    copiadoras,
    retroprojetores,
    impressoras,
    aparelhos_som,
    data_shows,
    fax,
    foto,
    computadores,
    computadores_adm,
    computadores_alunos,
    internet,
    banda_larga,
    funcionarios,
    alimentacao,
    aee,
    atividade_complementar,
    ensino_regular,
    reg_creche,
    reg_preescola,
    reg_fundamental8,
    reg_fundamental19,
    reg_medio_medio,
    reg_medio_integrado,
    reg_medio_normal,
    reg_medio_profissional,
    ensino_especial,
    esp_creche,
    esp_preescola,
    esp_fundamental8,
    esp_fundamental9,
    esp_medio_medio,
    esp_medio_integrado,
    esp_medio_normal,
    esp_medio_profissional,
    esp_eja_fundamental,
    esp_eja_medio,
    ensino_eja,
    eja_fundamental,
    eja_medio,
    eja_pro_jovem,
    ciclos,
    fim_de_semana,
    pedagogia_alternancia,
    ideb_ai,
    ideb_af,
    enem_portugues,
    enem_matematica,
    enem_humanas,
    enem_naturais,
    enem_redacao,
    enem_media_objetiva,
    enem_media_geral,
    socio_economico,
    formacao_docente,
    endereco,
    latitude,
    longitude,
    nome_titulo,
    situacao_funcionamento_txt,
    inicio_ano_txt,
    fim_ano_txt,
    dependencia_administrativa_txt,
    tipo_localizacao_txt,
    regulamentada_txt,
    partition_time 
    from `logical-essence-433414-r5.LAND_FLATFILE.api_escolas`
)
select * from cte_raw
    
    