config {
    type: "table",
    schema: "TRUSTED_FLATFILE",
    tags: ['estatisticas_full', 'processo_full'],
    name: "api_estatisticas_trusted",
    description: "Tabela criada a partir de RAW_FLATFILE.api_estatisticas",
    bigquery: {
        partitionBy: "DATETIME_TRUNC(partition_time, MONTH)",
        clusterBy: ['id']
    },
    dependencies: [
      "api_estatisticas_raw"
    ]
}

WITH latest_partition AS (
  SELECT MAX(partition_time) as max_partition_time
  from `logical-essence-433414-r5.RAW_FLATFILE.api_estatisticas_raw`
)

SELECT 
  CAST(id AS STRING) AS id,
  CAST(ano AS INT64) AS ano,
  CAST(tipo_local AS STRING) AS tipo_local,
  CAST(nome_local AS STRING) AS nome_local,
  CAST(cod_municipio AS INT64) AS cod_municipio,
  CAST(melhores AS INT64) AS melhores,
  CAST(situacao_funcionamento_atividade AS FLOAT64) AS situacao_funcionamento_atividade,
  CAST(situacao_funcionamento_paralisada AS FLOAT64) AS situacao_funcionamento_paralisada,
  CAST(situacao_funcionamento_extinta AS FLOAT64) AS situacao_funcionamento_extinta,
  CAST(situacao_funcionamento_extinta_ano_anterior AS FLOAT64) AS situacao_funcionamento_extinta_ano_anterior,
  CAST(situacao_funcionamento_nao_informado AS FLOAT64) AS situacao_funcionamento_nao_informado,
  CAST(dependencia_administrativa_federal AS FLOAT64) AS dependencia_administrativa_federal,
  CAST(dependencia_administrativa_estadual AS FLOAT64) AS dependencia_administrativa_estadual,
  CAST(dependencia_administrativa_municipal AS FLOAT64) AS dependencia_administrativa_municipal,
  CAST(dependencia_administrativa_privada AS FLOAT64) AS dependencia_administrativa_privada,
  CAST(tipo_localizacao_rural AS FLOAT64) AS tipo_localizacao_rural,
  CAST(tipo_localizacao_urbana AS FLOAT64) AS tipo_localizacao_urbana,
  CAST(regulamentada_sim AS FLOAT64) AS regulamentada_sim,
  CAST(regulamentada_nao AS FLOAT64) AS regulamentada_nao,
  CAST(regulamentada_tramitacao AS FLOAT64) AS regulamentada_tramitacao,
  CAST(agua_filtrada AS FLOAT64) AS agua_filtrada,
  CAST(agua_publica AS FLOAT64) AS agua_publica,
  CAST(agua_poco_artesiano AS FLOAT64) AS agua_poco_artesiano,
  CAST(agua_cacimba AS FLOAT64) AS agua_cacimba,
  CAST(agua_rio AS FLOAT64) AS agua_rio,
  CAST(agua_inexistente AS FLOAT64) AS agua_inexistente,
  CAST(agua_nao_informado AS FLOAT64) AS agua_nao_informado,
  CAST(energia_publica AS FLOAT64) AS energia_publica,
  CAST(energia_gerador AS FLOAT64) AS energia_gerador,
  CAST(energia_outros AS FLOAT64) AS energia_outros,
  CAST(energia_inexistente AS FLOAT64) AS energia_inexistente,
  CAST(energia_nao_informado AS FLOAT64) AS energia_nao_informado,
  CAST(esgoto_publico AS FLOAT64) AS esgoto_publico,
  CAST(esgoto_fossa AS FLOAT64) AS esgoto_fossa,
  CAST(esgoto_inexistente AS FLOAT64) AS esgoto_inexistente,
  CAST(esgoto_nao_informado AS FLOAT64) AS esgoto_nao_informado,
  CAST(lixo_coleta_periodica AS FLOAT64) AS lixo_coleta_periodica,
  CAST(lixo_queima AS FLOAT64) AS lixo_queima,
  CAST(lixo_joga_outra_area AS FLOAT64) AS lixo_joga_outra_area,
  CAST(lixo_recicla AS FLOAT64) AS lixo_recicla,
  CAST(lixo_enterra AS FLOAT64) AS lixo_enterra,
  CAST(lixo_outros AS FLOAT64) AS lixo_outros,
  CAST(lixo_nao_informado AS FLOAT64) AS lixo_nao_informado,
  CAST(sala_diretoria AS FLOAT64) AS sala_diretoria,
  CAST(sala_professores AS FLOAT64) AS sala_professores,
  CAST(laboratorio_informatica AS FLOAT64) AS laboratorio_informatica,
  CAST(laboratorio_ciencias AS FLOAT64) AS laboratorio_ciencias,
  CAST(atendimento_especial AS FLOAT64) AS atendimento_especial,
  CAST(quadra_coberta AS FLOAT64) AS quadra_coberta,
  CAST(quadra_descoberta AS FLOAT64) AS quadra_descoberta,
  CAST(cozinha AS FLOAT64) AS cozinha,
  CAST(biblioteca AS FLOAT64) AS biblioteca,
  CAST(sala_leitura AS FLOAT64) AS sala_leitura,
  CAST(parque_infantil AS FLOAT64) AS parque_infantil,
  CAST(bercario AS FLOAT64) AS bercario,
  CAST(sanitario_fora_predio AS FLOAT64) AS sanitario_fora_predio,
  CAST(sanitario_dentro_predio AS FLOAT64) AS sanitario_dentro_predio,
  CAST(sanitario_educ_infant AS FLOAT64) AS sanitario_educ_infant,
  CAST(sanitario_pne AS FLOAT64) AS sanitario_pne,
  CAST(dependencias_pne AS FLOAT64) AS dependencias_pne,
  CAST(secretaria AS FLOAT64) AS secretaria,
  CAST(banheiro_chuveiro AS FLOAT64) AS banheiro_chuveiro,
  CAST(refeitorio AS FLOAT64) AS refeitorio,
  CAST(despensa AS FLOAT64) AS despensa,
  CAST(almoxarifado AS FLOAT64) AS almoxarifado,
  CAST(auditorio AS FLOAT64) AS auditorio,
  CAST(patio_coberto AS FLOAT64) AS patio_coberto,
  CAST(patio_descoberto AS FLOAT64) AS patio_descoberto,
  CAST(alojamento_aluno AS FLOAT64) AS alojamento_aluno,
  CAST(alojamento_professor AS FLOAT64) AS alojamento_professor,
  CAST(area_verde AS FLOAT64) AS area_verde,
  CAST(lavanderia AS FLOAT64) AS lavanderia,
  CAST(salas_existentes AS FLOAT64) AS salas_existentes,
  CAST(salas_utilizadas AS FLOAT64) AS salas_utilizadas,
  CAST(televisores AS FLOAT64) AS televisores,
  CAST(video_cassetes AS FLOAT64) AS video_cassetes,
  CAST(dvds AS FLOAT64) AS dvds,
  CAST(parabolicas AS FLOAT64) AS parabolicas,
  CAST(copiadoras AS FLOAT64) AS copiadoras,
  CAST(retroprojetores AS FLOAT64) AS retroprojetores,
  CAST(impressoras AS FLOAT64) AS impressoras,
  CAST(aparelhos_som AS FLOAT64) AS aparelhos_som,
  CAST(datashows AS FLOAT64) AS datashows,
  CAST(fax AS FLOAT64) AS fax,
  CAST(foto AS FLOAT64) AS foto,
  CAST(computadores AS FLOAT64) AS computadores,
  CAST(computadores_adm AS FLOAT64) AS computadores_adm,
  CAST(computadores_alunos AS FLOAT64) AS computadores_alunos,
  CAST(internet AS FLOAT64) AS internet,
  CAST(banda_larga AS FLOAT64) AS banda_larga,
  CAST(ideb_ai AS FLOAT64) AS ideb_ai,
  CAST(ideb_af AS FLOAT64) AS ideb_af,
  CAST(enem_portugues AS FLOAT64) AS enem_portugues,
  CAST(enem_matematica AS FLOAT64) AS enem_matematica,
  CAST(enem_humanas AS FLOAT64) AS enem_humanas,
  CAST(enem_naturais AS FLOAT64) AS enem_naturais,
  CAST(enem_redacao AS FLOAT64) AS enem_redacao,
  CAST(enem_media_objetiva AS FLOAT64) AS enem_media_objetiva,
  CAST(enem_media_geral AS FLOAT64) AS enem_media_geral,
  CAST(formacao_docente AS FLOAT64) AS formacao_docente,
  partition_time
FROM `logical-essence-433414-r5.RAW_FLATFILE.api_estatisticas_raw`
WHERE partition_time = (SELECT max_partition_time from latest_partition)



