config {
    type: "incremental",
    schema: "RAW_FLATFILE",
    tags: ['estatisticas_full', 'processo_full'],
    name: "api_estatisticas_raw",
    description: "Tabela criada a partir de LAND_FLATFILE.api_estatisticas",
    bigquery: {
        partitionBy: "DATETIME_TRUNC(partition_time, MONTH)",
        clusterBy: ['id']
    }
}

with cte_stat as (
    select 
    id,
    ano,
    tipo_local,
    nome_local,
    cod_municipio,
    melhores,
    situacao_funcionamento_atividade,
    situacao_funcionamento_paralisada,
    situacao_funcionamento_extinta,
    situacao_funcionamento_extinta_ano_anterior,
    situacao_funcionamento_nao_informado,
    dependencia_administrativa_federal,
    dependencia_administrativa_estadual,
    dependencia_administrativa_municipal,
    dependencia_administrativa_privada,
    tipo_localizacao_rural,
    tipo_localizacao_urbana,
    regulamentada_sim,
    regulamentada_nao,
    regulamentada_tramitacao,
    agua_filtrada,
    agua_publica,
    agua_poco_artesiano,
    agua_cacimba,
    agua_rio,
    agua_inexistente,
    agua_nao_informado,
    energia_publica,
    energia_gerador,
    energia_outros,
    energia_inexistente,
    energia_nao_informado,
    esgoto_publico,
    esgoto_fossa,
    esgoto_inexistente,
    esgoto_nao_informado,
    lixo_coleta_periodica,
    lixo_queima,
    lixo_joga_outra_area,
    lixo_recicla,
    lixo_enterra,
    lixo_outros,
    lixo_nao_informado,
    sala_diretoria,
    sala_professores,
    laboratorio_informatica,
    laboratorio_ciencias,
    atendimento_especial,
    quadra_coberta,
    quadra_descoberta,
    cozinha,
    biblioteca,
    sala_leitura,
    parque_infantil,
    bercario,
    sanitario_fora_predio,
    sanitario_dentro_predio,
    sanitario_educ_infant,
    sanitario_pne,
    dependencias_pne,
    secretaria,
    banheiro_chuveiro,
    refeitorio,
    despensa,
    almoxarifado,
    auditorio,
    patio_coberto,
    patio_descoberto,
    alojamento_aluno,
    alojamento_professor,
    area_verde,
    lavanderia,
    salas_existentes,
    salas_utilizadas,
    televisores,
    video_cassetes,
    dvds,
    parabolicas,
    copiadoras,
    retroprojetores,
    impressoras,
    aparelhos_som,
    datashows,
    fax,
    foto,
    computadores,
    computadores_adm,
    computadores_alunos,
    internet,
    banda_larga,
    ideb_ai,
    ideb_af,
    enem_portugues,
    enem_matematica,
    enem_humanas,
    enem_naturais,
    enem_redacao,
    enem_media_objetiva,
    enem_media_geral,
    formacao_docente,
    partition_time
    from `logical-essence-433414-r5.LAND_FLATFILE.api_estatisticas` 
)

select * from cte_stat